# Generated by Django 2.2.5 on 2019-09-04 17:58

from django.db import migrations, models
import econapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('econapp', '0003_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to=econapp.models.image_folder),
        ),
    ]
